# Basic Python

## 1. Split this string

In [30]:
s='Hi there Sam'
words=s.split(' ')
words

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [2]:
print("The diameter of Earth is {} kilometers".format("12742"))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [9]:
movies={
  "Horror":{
    "name":"Hello",
    "year":2004
  },
  "Comedy":{
    "name":"Tobias",
    "year":2007
  },
  "Romance":{
    "name":"Titanic",
    "year":1998
  }
}
for key,values in movies.items():
  for k,v in values.items():
    if v=='Hello':
      print(v)

Hello


# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
array=np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [15]:
List=[]
for i in range(20,36):
  if(i%2==0):
    List.append(i)
arr=np.array(List)
arr

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [23]:
a=np.array([1,2,3])
b=np.array([4,5,6])
arr=np.concatenate((a,b))
arr

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [24]:
import pandas as pd

In [26]:
data={'Name':['Ray','Hafna','Thafseel'],
        'marks': [99,100,99]}
df=pd.DataFrame(data)
df

Name  marks
0       Ray     99
1     Hafna    100
2  Thafseel     99

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [27]:
import datetime

In [28]:
test_time=datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
date_generated=pd.date_range(test_time,periods=41)
date_generated

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [29]:
lists=[[1,'Ray',21],[2,'Hafna',21],[3,'Thafseel',21],[4,'Namrritha',20]]
df=pd.DataFrame(lists,columns=['S.No','Name','Age'])
df

S.No       Name  Age
0     1        Ray   21
1     2      Hafna   21
2     3   Thafseel   21
3     4  Namrritha   20